movie_library/models.py
from dataclasses import dataclass, field
from datetime import datetime
from typing import List

@dataclass
class Movie:
    _id: str
    title: str
    director: str
    year: int
    cast: List[str] = field(default_factory=list)
    series: List[str] = field(default_factory=list)
    last_watched: datetime = None
    tags: List[str] = field(default_factory=list)
    rating: int =0
    video_link: str = None
    description:str=None
    user_id: str= None

@dataclass
class User:
    _id: str
    email: str
    password: str

movie_library/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField, TextAreaField, URLField, PasswordField
from wtforms.validators import NumberRange, InputRequired, Email, Length, EqualTo

class MovieForm(FlaskForm):
    title=StringField("Title", validators=[InputRequired()])
    director=StringField("Director", validators=[InputRequired()])

    year=IntegerField("Year", validators=[InputRequired(), NumberRange(min=1878,message="Enter year in yyyy format")])

    submit=SubmitField("Add Movie")

class StringListField(TextAreaField):
    def _value(self):
        if self.data:
            return "\n".join(self.data)
        else:
            return ""
    def process_formdata(self, valuelist):
        if valuelist and valuelist[0]:
            self.data=[line.strip() for line in valuelist[0].split('\n')]
        else:
            self.data=[]


class ExtendedMovieForm(MovieForm):
    cast = StringListField("Cast")
    series=StringListField('Series')
    tags=StringListField("Tags")
    description= StringField("Description")
    video_link=URLField("Video link")

    submit=SubmitField("Submit")

class RegisterForm(FlaskForm):
    email=StringField("Email", validators=[InputRequired(), Email()])
    password=PasswordField("Password", validators=[InputRequired(), Length(min=4, message="Your password must contain atleast 4 character.")])
    confirm_password=PasswordField("Confirm password", validators=[InputRequired(), EqualTo("password", message="Password dosen't match.")])
    submit=SubmitField("Reegister")

class LoginForm(FlaskForm):
    email=StringField("Email", validators=[InputRequired(), Email()])
    password=PasswordField("Password", validators=[InputRequired()])
    submit=SubmitField("Login")

movie_library/__init__.py
import os
from flask import Flask
from dotenv import load_dotenv
from pymongo import MongoClient


from movie_library.routes import pages

load_dotenv()


def create_app():
    app=Flask(__name__)
    app.config["MONGODB_URI"]=os.environ.get("MONGODB_URI")
    app.config['SECRET_KEY']=os.environ.get("SECRET_KEY")
    app.db=MongoClient(app.config["MONGODB_URI"]).get_default_database()
    app.register_blueprint(pages)
    return app

movie_library/routes.py
from flask import Blueprint, render_template, session, redirect, url_for, request, current_app, flash
from movie_library.forms import MovieForm, ExtendedMovieForm, RegisterForm, LoginForm
from movie_library.models import Movie, User
from dataclasses import asdict
import datetime
import uuid
from passlib.hash import pbkdf2_sha256
from functools import wraps

pages=Blueprint("pages", __name__, template_folder="templates", static_folder="static")


def login_required(route):
    @wraps(route)
    def route_wrapper(*args,**kwargs):
        if session.get('email') == None:
            return redirect(url_for('pages.login'))
        
        return route(*args,**kwargs)
    
    return route_wrapper


@pages.route("/")
@login_required
def index():
    movies_data=current_app.db.movie.find({'user_id':session.get('user_id')})
    movies=[Movie(**movie) for movie in movies_data]
    return render_template("index.html", title='Movies Watchlist', movies_data=movies)

@pages.route("/register", methods=["POST","GET"])
def register():
    if session.get('email'):
        return redirect(url_for("pages.index"))
    form = RegisterForm()
    
    if form.validate_on_submit():
        user= User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data)
        )
        current_app.db.user.insert_one(asdict(user))

        flash("User registered Successfully", "success")

        return redirect(url_for("pages.login"))
    
    return render_template("register.html", title="Movies Watchlist - Register", form=form)

@pages.route('/login', methods=['POST',"GET"])
def login():
    if session.get('email'):
        return redirect(url_for('pages.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user_data=current_app.db.user.find_one({"email":form.email.data})
        if not user_data:
            flash("Incorrect login credentials", category="danger")
            return redirect(url_for("pages.login"))
        user=User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session['user_id']=user._id
            session['email']=user.email

            return redirect(url_for('pages.index'))
        
        flash("Incorrect login credentials.", category="danger")
    
    return render_template('login.html', title='Movies Watchlist - Login', form=form)

@pages.route('/movie/<string:_id>')
@login_required
def movie(_id:str):
    movie_data=current_app.db.movie.find_one({'_id':_id, 'user_id':session.get('user_id')})
    movie=Movie(**movie_data)

    return render_template('movie_details.html',movie=movie)

@pages.route('/movie/<string:_id>/rate')
@login_required
def rate_movie(_id):
    rating=int(request.args.get('rating'))
    current_app.db.movie.update_one({'_id':_id}, {'$set':{'rating':rating}})
    return redirect(url_for("pages.movie",_id=_id))

@pages.route('/movie/<string:_id>/watch')
def watch_today(_id):
    current_app.db.movie.update_one({'_id':_id}, {'$set':{'last_watched':datetime.datetime.today()}})
    return redirect(url_for("pages.movie",_id=_id))

@pages.route("/add" ,methods=['GET','POST'])
@login_required
def add_movie():
    form=MovieForm()
    
    if form.validate_on_submit():
        movie=Movie(_id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data,
            user_id=session.get('user_id')
        )
        current_app.db.movie.insert_one(asdict(movie))
        return redirect(url_for("pages.index"))

    return render_template('new_movie.html',title="Movies Watchlist - Add Movie", form=form)

@pages.route("/edit/<string:_id>", methods=["POST","GET"])
@login_required
def edit_movie(_id):
    movie=Movie(**current_app.db.movie.find_one({"_id":_id}))
    form= ExtendedMovieForm(obj=movie)

    if form.validate_on_submit():
        movie.title=form.title.data
        movie.director=form.director.data
        movie.year=form.year.data
        movie.cast=form.cast.data
        movie.tags=form.tags.data
        movie.series=form.series.data
        movie.description=form.description.data
        movie.video_link=form.video_link.data

        current_app.db.movie.update_one({"_id":_id},{"$set":asdict(movie)})

        return redirect(url_for("pages.movie",_id=_id))
    else:
        return render_template("movie_form.html", movie=movie, form=form) 

@pages.route("/delete/movie/<string:_id>")
def delete_movie(_id):
    current_app.db.movie.delete_one({'_id':_id,'user_id':session.get('user_id')})
    return redirect(url_for('pages.index'))

@pages.route("/logout")
def logout():
    current_theme=session.get('theme')
    session.clear()
    session['theme']=current_theme
    return redirect(url_for('pages.login'))

@pages.route("/toggle-theme")
def toggle_theme():
    current_theme=session.get("theme")
    if current_theme=='dark':
        session['theme']='light'
    else:
        session['theme']='dark'
    return redirect(request.args.get("current_page"))

movie_library/templates/index.html
{% extends 'layout.html' %}
{% from 'macros/svgs.html' import delete %}
{% block head_content %}
<link rel="stylesheet" href="{{url_for('static',filename='CSS/movies.css')}}">
{% endblock %}

{% block main_content %}
{% if movies_data %}
<table class="table">
    <colgroup>
        <col style="width: 55%;">
        <col style="width: 20%;">
        <col style="width: 15%;">
        <col style="width: 10%;">
    </colgroup>
    <thead>
        <th class="table__cell table__cell--header">Title</th>
        <th class="table__cell table__cell--header">Release</th>
        <th class="table__cell table__cell--header"></th>
        <th class="table__cell table__cell--header"></th>
    </thead>
    <tbody>
        {% for movie in movies_data %}
        <tr>
            <td class="table__cell">
                <p class="table__movieTitle">{{movie.title}}</p>
                <p class="table__movieDirector">{{movie.director}}</p>
            </td>
            <td class="table__cell">{{movie.year}}</td>
            <td class="table__cell"><a href="{{url_for('pages.movie',_id=movie._id)}}" class="table__link">View</a></td>
            <td class="table__cell"><a href="{{url_for('pages.delete_movie',_id=movie._id)}}"
                    class="table__link table__link--delete">{{delete("delete")}}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="table__empty">
    You haven't added any movies yet.
    <a href="{{url_for('pages.add_movie')}}" class="link">Add one</a>
</p>
{% endif %}
<a href="{{url_for('pages.add_movie')}}" class="button button--add">
    <span>+</span>
</a>
{% endblock %}

movie_library/templates/layout.html
{% from 'macros/nav.html' import header %}
{% from 'macros/footer.html' import footer%}
<!DOCTYPE html>
<html lang="en" class="{{'dark-mode' if session.get('theme')=='dark'}}">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Edu+NSW+ACT+Foundation:wght@400;500;600;700&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{{url_for('static',filename='CSS/reset.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='CSS/main.css')}}">
    <link rel="apple-touch-icon" sizes="57x57" href="{{url_for('static',filename='favicon//apple-icon-57x57.png')}}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{url_for('static',filename='favicon/apple-icon-60x60.png')}}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{url_for('static',filename='favicon//apple-icon-72x72.png')}}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{url_for('static',filename='favicon//apple-icon-76x76.png')}}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{url_for('static',filename='favicon/apple-icon-114x114.png')}}">
    <link rel="apple-touch-icon" sizes="120x120"
        href="{{url_for('static',filename='favicon//apple-icon-120x120.png')}}">
    <link rel="apple-touch-icon" sizes="144x144"
        href="{{url_for('static',filename='favicon//apple-icon-144x144.png')}}">
    <link rel="apple-touch-icon" sizes="152x152"
        href="{{url_for('static',filename='favicon//apple-icon-152x152.png')}}">
    <link rel="apple-touch-icon" sizes="180x180"
        href="{{url_for('static',filename='favicon//apple-icon-180x180.png')}}">
    <link rel="icon" type="image/png" sizes="192x192"
        href="{{url_for('static',filename='favicon//android-icon-192x192.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static',filename='favicon//favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{url_for('static',filename='favicon//favicon-96x96.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static',filename='favicon//favicon-16x16.png')}}">
    <link rel="manifest" href="{{url_for('static',filename='favicon//manifest.json')}}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    {% block head_content %}
    {% endblock %}
</head>

<body>
    {{header(session.get("email"),session.get("theme"))}}
    <main class="main">
        {% block main_content %}
        {% endblock %}
    </main>
    {{ footer() }}
</body>

</html>

movie_library/templates/login.html
{% extends 'layout.html' %}
{% from 'macros/fields.html' import render_text_field %}

{% block head_content %}
<link rel="stylesheet" href="{{url_for('static',filename='CSS/forms.css')}}">
{% endblock %}

{% block main_content %}
<form name="login" method="POST" class="form" novalidate>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}
    <span class="form__flash form__flash--{{category}}">{{message}}</span>
    {% endfor %}
    {% endwith %}

    <div class="form__container">
        {{form.hidden_tag()}}
        {{render_text_field(form.email)}}
        {{render_text_field(form.password)}}
        <span class="form__small">Don't have an account? <a href="{{url_for('pages.register')}}"
                class="form__link">Register here.</a></span>
        <div>
            {{form.submit(class_="button button--form")}}
        </div>
    </div>
</form>
{% endblock %}

movie_library/templates/macros/fields.html
{% macro render_text_field(field) %}
<div class="form__group">
    {{field.label(class_="form__label")}}
    {{field(class_="form__field")}}

    {% for error in field.errors %}
    <span class="form__error">{{error}}</span>
    {% endfor %}
</div>
{% endmacro %}

{% macro render_area_field(field) %}
<div class="form__group">
    {{field.label(class_="form__label")}}
    {{field(rows=4, class_="form__field", style="resize:none ")}}

    {% for error in field.errors %}
    <span class="form__error">{{error}}</span>
    {% endfor %}
</div>
{% endmacro %}

movie_library/templates/macros/footer.html
{% macro footer() %}
<footer class="footer">
    <small>Copyright &copy;2022. Movies Watchlist. All rights reserved.</small>
</footer>
{% endmacro %}

movie_library/templates/macros/nav.html
{% from 'macros/svgs.html' import sun,moon %}
{% macro header(email,theme) %}
<header class="header">
    <div class="nav-container">
        <a href="{{url_for('pages.index')}}" class="header__logo">
            <svg xmlns="http://www.w3.org/2000/svg" class="logo__icon" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
            </svg>
            <span class="logo__name">
                Watchlist
            </span>
        </a>
        <nav class="nav">
            {% if not email %}
            <a href="{{url_for('pages.login')}}"
                class="nav__links {{'nav__links--active' if request.path==url_for('pages.login')}}">
                <span class="nav__items">Log In</span>
            </a>
            <a href="{{url_for('pages.register')}}"
                class="nav__links {{'nav__links--active' if request.path == url_for('pages.register')}}">
                <span class="nav__items">Register</span>
            </a>
            {% else %}
            <a href="{{url_for('pages.index')}}"
                class="nav__links {{'nav__links--active' if request.path == url_for('pages.index')}}">
                <span class="nav__items">Movies</span>
            </a>
            <a href="{{url_for('pages.logout')}}" class="nav__links">
                <span class="nav__items">Log Out</span>
            </a>
            {% endif %}
            <a href="{{url_for('pages.toggle_theme', current_page=request.path)}}" class="nav__links">
                <span class="nav__items">
                    {% if theme == 'dark' %}
                    {{sun('nav__icon')}}
                    {% else %}
                    {{moon('nav__icon')}}
                    {% endif %}
                </span>
            </a>
        </nav>
    </div>
</header>
{% endmacro %}

movie_library/templates/macros/svgs.html
{% macro star(class_) %}
<i class="fa-solid fa-star {{class_}}"></i>
{% endmacro %}

{% macro pencil(class_) %}
<i class="fa-solid fa-pencil {{class_}}"></i>
{% endmacro %}

{% macro moon(class_) %}
<i class="fa-solid fa-moon {{class_}}"></i>
{% endmacro %}

{% macro sun(class_) %}
<i class="fa-sharp fa-solid fa-sun {{class_}}"></i>
{% endmacro %}
{% macro delete(_class) %}
<i class="fa-regular fa-trash-can {{_class}}"></i>
{% endmacro %}

movie_library/templates/movie_details.html
{% from "macros/svgs.html" import star, pencil %}

{% extends "layout.html" %}

{%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='CSS/movie_details.css') }}" />
{% endblock %}

{% block main_content %}
<div class="container">
    <header class="movie__header">
        <div class="header__row">
            <div class="movie__name">
                <h1>{{ movie.title }}</h1>
                <div class="movie__rating">
                    {% for i in range(5) %}
                    <a href="{{url_for('pages.rate_movie',_id=movie._id,rating=i+1)}}" class="rating__link">{{star('star
                        '+('star--filled' if movie.rating > i else ''))}}</a>
                    {% endfor %}
                </div>
            </div>
            <div class="movie__watched">
                {% if movie.last_watched %}
                <p>
                    Last watched: <a href="{{url_for('pages.watch_today', _id=movie._id)}}" class="watched__link">
                        <time datetime="{{ movie.last_watched }}">{{movie.last_watched.strftime("%d %b %Y")}}</time>
                    </a>
                </p>
                {% else %}
                <p><a href="{{url_for('pages.watch_today', _id=movie._id)}}" class="watched__link">Not watched yet</a>
                </p>
                {% endif %}
                <a class="movie__edit" href="{{url_for('pages.edit_movie',_id=movie._id)}}">Edit {{ pencil("pencil")
                    }}</a>
            </div>
        </div>
        <div class="header__row">
            <ul class="movie__tags">
                {% for tag in movie.tags %}
                <li class="movie__tag">{{ tag }}</li>
                {% endfor %}
            </ul>
        </div>
    </header>
    {% if movie.video_link %}
    <iframe class="movie__video" src="{{ movie.video_link }}" title="YouTube video player" frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
    </iframe>
    {% endif %}

    {% if movie.description %}
    <p class="movie__description">{{ movie.description }}</p>
    {% else %}
    <p class="movie__description">No description yet. <a class="link"
            href="{{url_for('pages.edit_movie',_id=movie._id)}}">Add one?</a></p>
    {% endif %}

    <div class="movie__meta">
        {% if movie.cast %}
        <div class="movie__casting">
            <h2>Casting</h2>
            <ul class="list">
                {% for actor in movie.cast %}
                <li class="list__item">{{ actor }}</li>
                {% endfor %}
                <ul>
        </div>
        {% endif %}
        {% if movie.series | length %}
        <div class="movie__series">
            <h2>Series</h2>
            <ul class="list">
                {% for movie_in_series in movie.series %}
                <li class="list__item">{{ movie_in_series }}</li>
                {% endfor %}
                <ul>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}
#

movie_library/templates/movie_form.html
{% extends 'layout.html' %}
{% from 'macros/fields.html' import render_text_field, render_area_field %}

{% block head_content %}
<link rel="stylesheet" href="{{url_for('static',filename='CSS/forms.css')}}">
{% endblock %}

{% block main_content %}
<form name="add_movie" method="POST" class="form" novalidate>
    <div class="form__container">
        {{form.hidden_tag()}}
        {{render_text_field(form.title)}}
        {{render_text_field(form.director)}}
        {{render_text_field(form.year)}}

        {{render_area_field(form.cast)}}
        {{render_area_field(form.series)}}
        {{render_area_field(form.tags)}}

        {{render_area_field(form.description)}}
        {{render_text_field(form.video_link)}}
        <div>
            {{form.submit(class_="button button--form")}}
        </div>
    </div>
</form>
{% endblock %}

movie_library/templates/new_movie.html
{% extends 'layout.html' %}
{% from 'macros/fields.html' import render_text_field %}

{% block head_content %}
<link rel="stylesheet" href="{{url_for('static',filename='CSS/forms.css')}}">
{% endblock %}

{% block main_content %}
<form name="add_movie" method="POST" class="form" novalidate>
    <div class="form__container">
        {{form.hidden_tag()}}
        {{render_text_field(form.title)}}
        {{render_text_field(form.director)}}
        {{render_text_field(form.year)}}
        <div>
            {{form.submit(class_="button button--form")}}
        </div>
    </div>
</form>
{% endblock %}

movie_library/templates/register.html
{% extends 'layout.html' %}
{% from 'macros/fields.html' import render_text_field %}

{% block head_content %}
<link rel="stylesheet" href="{{url_for('static',filename='CSS/forms.css')}}">
{% endblock %}

{% block main_content %}
<form name="register" method="POST" class="form" novalidate>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% for category, message in messages %}
    <span class="form__flash form__flash--{{category}}">{{message}}</span>
    {% endfor %}
    {% endwith %}

    <div class="form__container">
        {{form.hidden_tag()}}
        {{render_text_field(form.email)}}
        {{render_text_field(form.password)}}
        {{render_text_field(form.confirm_password)}}
        <span class="form__small">Already have an account? <a href="{{url_for('pages.login')}}" class="form__link">Log
                in
                here.</a></span>
        <div>
            {{form.submit(class_="button button--form")}}
        </div>
    </div>
</form>
{% endblock %}